version: "3.7"

services:
  ts-node-docker:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/usr/src/app/api/src
    container_name: ts-node-docker
    ports:
      - 8080:3000

  chat-server:
    build:
      context: ./chat/server
      dockerfile: Dockerfile
    volumes:
      - ./chat/server/src:/usr/src/app/chat/server/src/
    container_name: chat-server
    ports:
      - 8082:3000

  chat-client:
    build:
      context: ./chat/client
      dockerfile: Dockerfile
    volumes:
      - ./chat/client/src:/usr/src/app/chat/client/src/
    container_name: chat-client
    ports:
      - 5500:5500
    depends_on:
      - chat-server