version: "3.7"

services:
  ts-node-docker:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/usr/src/app/api/src
    container_name: ts-node-docker
    ports:
      - 8080:3000

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres/data:/home/postgres/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080 
