version: "3.7"

services:
  ts-node-docker:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/usr/src/app/api/src
      - /usr/src/app/api/node_modules
    container_name: ts-node-docker
    ports:
      - 8080:3000

  chat-server:
    build:
      context: ./chat/server
      dockerfile: Dockerfile.dev
    volumes:
      - ./chat/server/src:/usr/src/app/chat/server/src/
      - /usr/src/app/chat/server/node_modules
    container_name: chat-server
    ports:
      - 8082:3000

  chat-client:
    build:
      context: ./chat/client
      dockerfile: Dockerfile.dev
    volumes:
      - ./chat/client/src:/usr/src/app/chat/client/src/
      - /usr/src/app/chat/client/node_modules
    container_name: chat-client
    ports:
      - 5500:5500
    depends_on:
      - chat-server

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres/data:/home/postgres/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080 
