version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    container_name: ts-node-docker
    ports:
      - '3000:3000'
    command: npm run dev