name: Docker Image CI

on:
  push:
    branches:
      - main
      - github-action
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Deploy to server'
    steps:

    - uses: actions/checkout@v3
    - uses: arwynfr/actions-docker-context@v2
      with:
        docker_host: 'ssh://34.78.167.227'
        context_name: 'uni4all-remote'
        ssh_cert: ${{ secrets.SSH_CERT }}
        ssh_key: ${{ secrets.SSH_KEY }}
      env:
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        JWT_GENERATOR_KEY: ${{ secrets.JWT_GENERATOR_KEY }}
        JWT_PASS_RESET_KEY: ${{ secrets.JWT_PASS_RESET_KEY }}

    - run: docker context use uni4all-remote
    - run: COMPOSE_DOCKER_CLI_BUILD=0 docker-compose up -d --build
